version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./docker/web
    command: uwsgi --socket :8001 --module mysite.wsgi
    volumes:
      - ./backend:/code
      - ./backend/static:/static
    expose:
      - "8001"
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/static:/static
    depends_on:
      - web
